on: [push]
jobs:
  test:
    runs-on: scanner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: pip3 install checkov
      - name: Checkov
        run: checkov -d . -o sarif
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: ./results.sarif
