on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: pip3 install checkov
      - name: Checkov
        working-directory: /advanced-security-terraform
        run: checkov -d . -o sarif
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: ./results.sarif
